### ISSUE TITLE
Consider adding data file listing available resources?

### ISSUE THREAD

**Issue by johnmackintosh** [Public-Health-Scotland/phsopendata#10]
Would you consider providing a data file listing all resources available via this package, to assist with using the various `get` functions when performing an initial search of available data?

Being able to quickly list and view the available resources would keep the workflow within R and minimise disruption to search via the web interface

Best regards
John

**Comment by Moohan** [comment]
Should be simple enough, in fact, we already pull a list of dataset names when we try to suggest typo corrections: https://github.com/Public-Health-Scotland/phsopendata/blob/f263b4d49582f03e1f1d4a93c4b87e219bb50b1e/R/suggest_dataset_name.R#L8 

So that could just be bundled into a function which can be exposed to the user and also used at that point.
